export enum InscriptionStep {
  INITIAL = 'INITIAL',
  TERMS_ACCEPTANCE = 'TERMS_ACCEPTANCE',
  LOCATION_SELECTION = 'LOCATION_SELECTION',
  DATA_CONFIRMATION = 'DATA_CONFIRMATION',
  COMPLETED = 'COMPLETED'
} 