#!/bin/bash
# CORRECCIÓN DE TIMEZONE EN CONTENEDORES DOCKER

echo "🕐 CORRECCIÓN DE TIMEZONE - CONTENEDORES DOCKER"
echo "================================================="
echo "📅 Problema: Contenedores en UTC, usuarios en Argentina (ART)"
echo "🎯 Objetivo: Configurar timezone America/Argentina/Buenos_Aires"
echo ""

echo "🔍 ESTADO ACTUAL:"
echo "   Host timezone: $(timedatectl show -p Timezone --value)"
echo "   Backend container: $(docker exec mpd-concursos-backend date)"
echo "   MySQL container: $(docker exec mpd-concursos-mysql date)"
echo ""

echo "⚠️  ADVERTENCIA:"
echo "   Esta corrección requiere reinicio de contenedores"
echo "   ¿Desea continuar? (Este script solo muestra la solución)"
echo ""

echo "🔧 SOLUCIÓN RECOMENDADA:"
echo ""
echo "1. AGREGAR VARIABLES DE ENTORNO AL docker-compose.production.yml:"
echo ""
echo "   backend:"
echo "     environment:"
echo "       - TZ=America/Argentina/Buenos_Aires"
echo "       - JAVA_OPTS=-Duser.timezone=America/Argentina/Buenos_Aires"
echo ""
echo "   mysql:"
echo "     environment:"
echo "       - TZ=America/Argentina/Buenos_Aires"
echo ""
echo "2. MODIFICAR CONFIGURACIÓN DE SPRING BOOT:"
echo ""
echo "   spring.datasource.url=...&serverTimezone=America/Argentina/Buenos_Aires"
echo "   spring.jpa.properties.hibernate.jdbc.time_zone=America/Argentina/Buenos_Aires"
echo ""
echo "3. REINICIAR CONTENEDORES:"
echo ""
echo "   docker compose -f docker-compose.production.yml down"
echo "   docker compose -f docker-compose.production.yml up -d"
echo ""

echo "📋 VERIFICACIÓN POST-CORRECCIÓN:"
echo "   - Verificar que contenedores muestren hora Argentina"
echo "   - Probar nueva inscripción de prueba"
echo "   - Confirmar que timestamps sean correctos"
echo ""

echo "⚡ CORRECCIÓN INMEDIATA PARA GABRIELA LUIS:"
echo "   - Opción 1: Corrección manual del timestamp en BD"
echo "   - Opción 2: Aplicar nota explicativa en su expediente"
echo "   - Opción 3: Permitir reinscripción sin penalización"

