version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mpd-concursos-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mpd_concursos
      MYSQL_USER: mpd_user
      MYSQL_PASSWORD: mpd_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  backend:
    build: 
      context: ./concurso-backend
      dockerfile: Dockerfile
    container_name: mpd-concursos-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mpd_concursos?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=mpd_user
      - SPRING_DATASOURCE_PASSWORD=mpd_password
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql-data:
    name: mpd-concursos-mysql-data

networks:
  default:
    name: mpd-concursos-network
    driver: bridge
