version: '3.8'

services:
  backend:
    build: 
      context: ./concurso-backend
      dockerfile: Dockerfile
    container_name: mpd-concursos-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/app/data/concursosH2bd;MODE=MySQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
      - SPRING_DATASOURCE_USERNAME=semper
      - SPRING_DATASOURCE_PASSWORD=semper
      - JAVA_OPTS=-Xmx512m -Xms256m
    restart: always
    volumes:
      - concursos-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  concursos-data:
    name: mpd-concursos-data

networks:
  default:
    name: mpd-concursos-network
    driver: bridge
