version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mpd-concursos-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: mpd_concursos
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - mpd-concursos-network

  backend:
    build:
      context: ./concurso-backend
      dockerfile: Dockerfile
    container_name: mpd-concursos-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mpd_concursos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_MVC_CORS_ALLOWED_ORIGINS: http://localhost:8000,http://localhost:4200,http://149.50.132.23:8000
    ports:
      - "8080:8080"
    volumes:
      - document_storage:/app/document-storage
    networks:
      - mpd-concursos-network

  frontend:
    build:
      context: ./mpd-concursos-app-frontend
      dockerfile: Dockerfile
    container_name: mpd-concursos-frontend
    depends_on:
      - backend
    ports:
      - "8000:80"
    networks:
      - mpd-concursos-network

volumes:
  mysql_data:
  document_storage:

networks:
  mpd-concursos-network:
    driver: bridge 