export enum SecurityViolationType {
  FULLSCREEN_EXIT = 'FULLSCREEN_EXIT',
  FULLSCREEN_DENIED = 'FULLSCREEN_DENIED',
  TAB_SWITCH = 'TAB_SWITCH',
  KEYBOARD_SHORTCUT = 'KEYBOARD_SHORTCUT',
  CLIPBOARD_OPERATION = 'CLIPBOARD_OPERATION',
  INACTIVITY_TIMEOUT = 'INACTIVITY_TIMEOUT',
  NETWORK_VIOLATION = 'NETWORK_VIOLATION',
  SUSPICIOUS_BEHAVIOR = 'SUSPICIOUS_BEHAVIOR',
  TIME_MANIPULATION = 'TIME_MANIPULATION',
  TIME_DRIFT = 'TIME_DRIFT',
  SUSPICIOUS_ANSWER = 'SUSPICIOUS_ANSWER',
  ANSWER_TOO_FAST = 'ANSWER_TOO_FAST',
  ANSWER_TOO_SLOW = 'ANSWER_TOO_SLOW',
  SUSPICIOUS_PATTERN = 'SUSPICIOUS_PATTERN',
  POST_INCIDENT_VALIDATION_FAILED = 'POST_INCIDENT_VALIDATION_FAILED'
}

export interface SecurityViolation {
  type: SecurityViolationType;
  timestamp: string;
  details?: any;
  severity: 'LOW' | 'MEDIUM' | 'HIGH';
  actionTaken?: string;
}
