# Etapa de construcción
FROM node:20-slim AS builder

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de configuración
COPY package*.json ./

# Remove electron from devDependencies
RUN npm pkg delete devDependencies.electron

# Configure npm and install dependencies
RUN npm config set strict-ssl false \
    && npm config set registry "https://registry.npmjs.org/" \
    && npm install --no-audit --no-fund --legacy-peer-deps \
    --fetch-retries 5 \
    --fetch-retry-factor 2 \
    --fetch-retry-mintimeout 20000 \
    --fetch-retry-maxtimeout 120000

# Copiar el código fuente
COPY . .

# Construir la aplicación
RUN npm run start

# Etapa de producción
FROM nginx:alpine

# Copiar los archivos construidos
COPY --from=builder /app/dist/mpd-concursos-app-frontend/browser /usr/share/nginx/html

# Exponer el puerto 80
EXPOSE 80

# Iniciar nginx
CMD ["nginx", "-g", "daemon off;"]