
spring:
  // ...existing code...
  mvc:
    cors:
      allowed-origins: ${SPRING_MVC_CORS_ALLOWED_ORIGINS}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: Authorization,Content-Type
      allow-credentials: true
      max-age: 1800