server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
    
    location /health {
        access_log off;
        return 200 "maintenance mode - backend offline";
        add_header Content-Type text/plain;
    }
    
    # Desactivar logs para evitar spam de errores
    error_log /var/log/nginx/error.log crit;
    access_log /var/log/nginx/access.log;
}
